### ISSUE TITLE
Detekt is Now on GitHub, and depreciated on GitLab

### ISSUE THREAD

**Issue by sommersbenw** [codacy/codacy-detekt#15]
Detekt has marked their GitLab codebase as depreciated: https://gitlab.com/arturbosch/detekt

build.sbt should now point to GitHub: https://github.com/arturbosch/detekt

**Comment by lolgab** [comment]
I'm closing this since it is already solved. Now there are no more gitlab links in the repository.
Thank you for letting us know.

**Comment by sommersbenw** [comment]
@lolgab Are these entries not still pulling back from Gitlab?

https://github.com/codacy/codacy-detekt/blob/master/build.sbt#L38

**Comment by lolgab** [comment]
Yes, because they maintained their old gitlab groupid:
https://github.com/arturbosch/detekt/blob/629b92dc1fa980a9847d77d6e394dc48410913c3/build.gradle.kts#L79
